//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projecto_Final_PG4.Presentacion.SRComunicacionPersona {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaDTO", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
    [System.SerializableAttribute()]
    public partial class PersonaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_personaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_empleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((this.CelularField.Equals(value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsEmpleado {
            get {
                return this.EsEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EsEmpleadoField, value) != true)) {
                    this.EsEmpleadoField = value;
                    this.RaisePropertyChanged("EsEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_persona {
            get {
                return this.ID_personaField;
            }
            set {
                if ((this.ID_personaField.Equals(value) != true)) {
                    this.ID_personaField = value;
                    this.RaisePropertyChanged("ID_persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((this.TelefonoField.Equals(value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_empleado {
            get {
                return this.Tipo_empleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_empleadoField, value) != true)) {
                    this.Tipo_empleadoField = value;
                    this.RaisePropertyChanged("Tipo_empleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="PersonaDTO.ListaPersonas", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
        [System.SerializableAttribute()]
        public partial class ListaPersonas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO[] listaField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO[] lista {
                get {
                    return this.listaField;
                }
                set {
                    if ((object.ReferenceEquals(this.listaField, value) != true)) {
                        this.listaField = value;
                        this.RaisePropertyChanged("lista");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutoClienteDTO", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
    [System.SerializableAttribute()]
    public partial class AutoClienteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_Auto_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Auto_Cliente {
            get {
                return this.ID_Auto_ClienteField;
            }
            set {
                if ((this.ID_Auto_ClienteField.Equals(value) != true)) {
                    this.ID_Auto_ClienteField = value;
                    this.RaisePropertyChanged("ID_Auto_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AutoClienteDTO.ListaAutoCliente", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
        [System.SerializableAttribute()]
        public partial class ListaAutoCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO[] listaField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO[] lista {
                get {
                    return this.listaField;
                }
                set {
                    if ((object.ReferenceEquals(this.listaField, value) != true)) {
                        this.listaField = value;
                        this.RaisePropertyChanged("lista");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiciosDTO", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
    [System.SerializableAttribute()]
    public partial class ServiciosDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descripcion_servicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_servicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_tipo_servicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Servicio_seleccionadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion_servicio {
            get {
                return this.Descripcion_servicioField;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion_servicioField, value) != true)) {
                    this.Descripcion_servicioField = value;
                    this.RaisePropertyChanged("Descripcion_servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_servicio {
            get {
                return this.ID_servicioField;
            }
            set {
                if ((this.ID_servicioField.Equals(value) != true)) {
                    this.ID_servicioField = value;
                    this.RaisePropertyChanged("ID_servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_tipo_servicio {
            get {
                return this.ID_tipo_servicioField;
            }
            set {
                if ((this.ID_tipo_servicioField.Equals(value) != true)) {
                    this.ID_tipo_servicioField = value;
                    this.RaisePropertyChanged("ID_tipo_servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Servicio_seleccionado {
            get {
                return this.Servicio_seleccionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Servicio_seleccionadoField, value) != true)) {
                    this.Servicio_seleccionadoField = value;
                    this.RaisePropertyChanged("Servicio_seleccionado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ServiciosDTO.ListaServicios", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
        [System.SerializableAttribute()]
        public partial class ListaServicios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO[] listaField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO[] lista {
                get {
                    return this.listaField;
                }
                set {
                    if ((object.ReferenceEquals(this.listaField, value) != true)) {
                        this.listaField = value;
                        this.RaisePropertyChanged("lista");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiciosClienteDTO", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
    [System.SerializableAttribute()]
    public partial class ServiciosClienteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_Servicio_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Servicio_SeleccionadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Servicio_Cliente {
            get {
                return this.ID_Servicio_ClienteField;
            }
            set {
                if ((this.ID_Servicio_ClienteField.Equals(value) != true)) {
                    this.ID_Servicio_ClienteField = value;
                    this.RaisePropertyChanged("ID_Servicio_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Servicio_Seleccionado {
            get {
                return this.Servicio_SeleccionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Servicio_SeleccionadoField, value) != true)) {
                    this.Servicio_SeleccionadoField = value;
                    this.RaisePropertyChanged("Servicio_Seleccionado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ServiciosClienteDTO.ListaServiciosCliente", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
        [System.SerializableAttribute()]
        public partial class ListaServiciosCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO[] listaField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO[] lista {
                get {
                    return this.listaField;
                }
                set {
                    if ((object.ReferenceEquals(this.listaField, value) != true)) {
                        this.listaField = value;
                        this.RaisePropertyChanged("lista");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomotoresDTO", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
    [System.SerializableAttribute()]
    public partial class AutomotoresDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CilindrajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsClasicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsManualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsMensajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsTransEspeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsTransPublicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_automotorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tiene_contenedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_combustibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_vehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cilindraje {
            get {
                return this.CilindrajeField;
            }
            set {
                if ((this.CilindrajeField.Equals(value) != true)) {
                    this.CilindrajeField = value;
                    this.RaisePropertyChanged("Cilindraje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsClasica {
            get {
                return this.EsClasicaField;
            }
            set {
                if ((object.ReferenceEquals(this.EsClasicaField, value) != true)) {
                    this.EsClasicaField = value;
                    this.RaisePropertyChanged("EsClasica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsManual {
            get {
                return this.EsManualField;
            }
            set {
                if ((object.ReferenceEquals(this.EsManualField, value) != true)) {
                    this.EsManualField = value;
                    this.RaisePropertyChanged("EsManual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsMensajero {
            get {
                return this.EsMensajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.EsMensajeroField, value) != true)) {
                    this.EsMensajeroField = value;
                    this.RaisePropertyChanged("EsMensajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsTransEspe {
            get {
                return this.EsTransEspeField;
            }
            set {
                if ((object.ReferenceEquals(this.EsTransEspeField, value) != true)) {
                    this.EsTransEspeField = value;
                    this.RaisePropertyChanged("EsTransEspe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsTransPublico {
            get {
                return this.EsTransPublicoField;
            }
            set {
                if ((object.ReferenceEquals(this.EsTransPublicoField, value) != true)) {
                    this.EsTransPublicoField = value;
                    this.RaisePropertyChanged("EsTransPublico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_automotor {
            get {
                return this.ID_automotorField;
            }
            set {
                if ((this.ID_automotorField.Equals(value) != true)) {
                    this.ID_automotorField = value;
                    this.RaisePropertyChanged("ID_automotor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tiene_contenedor {
            get {
                return this.Tiene_contenedorField;
            }
            set {
                if ((object.ReferenceEquals(this.Tiene_contenedorField, value) != true)) {
                    this.Tiene_contenedorField = value;
                    this.RaisePropertyChanged("Tiene_contenedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_combustible {
            get {
                return this.Tipo_combustibleField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_combustibleField, value) != true)) {
                    this.Tipo_combustibleField = value;
                    this.RaisePropertyChanged("Tipo_combustible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_vehiculo {
            get {
                return this.Tipo_vehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_vehiculoField, value) != true)) {
                    this.Tipo_vehiculoField = value;
                    this.RaisePropertyChanged("Tipo_vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AutomotoresDTO.ListaAutomotores", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
        [System.SerializableAttribute()]
        public partial class ListaAutomotores : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO[] listaField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO[] lista {
                get {
                    return this.listaField;
                }
                set {
                    if ((object.ReferenceEquals(this.listaField, value) != true)) {
                        this.listaField = value;
                        this.RaisePropertyChanged("lista");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoServicioDTO", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
    [System.SerializableAttribute()]
    public partial class TipoServicioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descripcion_servicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_tipo_servicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion_servicio {
            get {
                return this.Descripcion_servicioField;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion_servicioField, value) != true)) {
                    this.Descripcion_servicioField = value;
                    this.RaisePropertyChanged("Descripcion_servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_tipo_servicio {
            get {
                return this.ID_tipo_servicioField;
            }
            set {
                if ((this.ID_tipo_servicioField.Equals(value) != true)) {
                    this.ID_tipo_servicioField = value;
                    this.RaisePropertyChanged("ID_tipo_servicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="TipoServicioDTO.ListaTipoServicios", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
        [System.SerializableAttribute()]
        public partial class ListaTipoServicios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO[] listaField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO[] lista {
                get {
                    return this.listaField;
                }
                set {
                    if ((object.ReferenceEquals(this.listaField, value) != true)) {
                        this.listaField = value;
                        this.RaisePropertyChanged("lista");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRComunicacionPersona.IPrimerServicio")]
    public interface IPrimerServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarPersonaResponse")]
        void InsertarPersona(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarPersonaResponse")]
        System.Threading.Tasks.Task InsertarPersonaAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarPersonaResponse")]
        void ModificarPersona(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarPersonaResponse")]
        System.Threading.Tasks.Task ModificarPersonaAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarPersonaResponse")]
        void EliminarPersona(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarPersonaResponse")]
        System.Threading.Tasks.Task EliminarPersonaAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerPersonaID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerPersonaIDResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO ObtenerPersonaID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerPersonaID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerPersonaIDResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO> ObtenerPersonaIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosPersona", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosPersonaResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO.ListaPersonas ObtenerTodosPersona();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosPersona", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosPersonaResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO.ListaPersonas> ObtenerTodosPersonaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarAutoClienteResponse")]
        void InsertarAutoCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarAutoClienteResponse")]
        System.Threading.Tasks.Task InsertarAutoClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarAutoClienteResponse")]
        void ModificarAutoCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cleinte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarAutoClienteResponse")]
        System.Threading.Tasks.Task ModificarAutoClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cleinte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarAutoClienteResponse")]
        void EliminarAutoCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarAutoClienteResponse")]
        System.Threading.Tasks.Task EliminarAutoClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerAutoClienteID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerAutoClienteIDResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO ObtenerAutoClienteID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerAutoClienteID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerAutoClienteIDResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO> ObtenerAutoClienteIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosAutoClientes", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosAutoClientesResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO.ListaAutoCliente ObtenerTodosAutoClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosAutoClientes", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosAutoClientesResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO.ListaAutoCliente> ObtenerTodosAutoClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarServicioResponse")]
        void InsertarServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarServicioResponse")]
        System.Threading.Tasks.Task InsertarServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarServicioResponse")]
        void ModificarServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarServicioResponse")]
        System.Threading.Tasks.Task ModificarServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarServicioResponse")]
        void EliminarServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarServicioResponse")]
        System.Threading.Tasks.Task EliminarServicioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerServicioID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerServicioIDResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO ObtenerServicioID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerServicioID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerServicioIDResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO> ObtenerServicioIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosServicioResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO.ListaServicios ObtenerTodosServicio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosServicioResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO.ListaServicios> ObtenerTodosServicioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarServicioCliente", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarServicioClienteResponse")]
        void InsertarServicioCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarServicioCliente", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarServicioClienteResponse")]
        System.Threading.Tasks.Task InsertarServicioClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarServicioCliente", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarServicioClienteResponse")]
        void ModificarServicioCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarServicioCliente", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarServicioClienteResponse")]
        System.Threading.Tasks.Task ModificarServicioClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarServicioCliente", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarServicioClienteResponse")]
        void EliminarServicioCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarServicioCliente", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarServicioClienteResponse")]
        System.Threading.Tasks.Task EliminarServicioClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerServicioClienteID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerServicioClienteIDResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO ObtenerServicioClienteID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerServicioClienteID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerServicioClienteIDResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO> ObtenerServicioClienteIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosServicioCliente", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosServicioClienteResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO.ListaServiciosCliente ObtenerTodosServicioCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosServicioCliente", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosServicioClienteResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO.ListaServiciosCliente> ObtenerTodosServicioClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarAutomotor", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarAutomotorResponse")]
        void InsertarAutomotor(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO automotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarAutomotor", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarAutomotorResponse")]
        System.Threading.Tasks.Task InsertarAutomotorAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO automotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarAutomotor", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarAutomotorResponse")]
        void ModificarAutomotor(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO automotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarAutomotor", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarAutomotorResponse")]
        System.Threading.Tasks.Task ModificarAutomotorAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO automotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarAutomotor", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarAutomotorResponse")]
        void EliminarAutomotor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarAutomotor", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarAutomotorResponse")]
        System.Threading.Tasks.Task EliminarAutomotorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerAutomotorID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerAutomotorIDResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO ObtenerAutomotorID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerAutomotorID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerAutomotorIDResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO> ObtenerAutomotorIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosAutomotores", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosAutomotoresResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO.ListaAutomotores ObtenerTodosAutomotores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosAutomotores", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosAutomotoresResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO.ListaAutomotores> ObtenerTodosAutomotoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarTipoServicio", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarTipoServicioResponse")]
        void InsertarTipoServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO tipoSrv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarTipoServicio", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarTipoServicioResponse")]
        System.Threading.Tasks.Task InsertarTipoServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO tipoSrv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarTipoServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarTipoServicioResponse")]
        void ModificarTipoServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO tipoSrv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarTipoServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarTipoServicioResponse")]
        System.Threading.Tasks.Task ModificarTipoServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO tipoSrv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarTipoServicio", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarTipoServicioResponse")]
        void EliminarTipoServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarTipoServicio", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarTipoServicioResponse")]
        System.Threading.Tasks.Task EliminarTipoServicioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTipoServicioID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTipoServicioIDResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO ObtenerTipoServicioID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTipoServicioID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTipoServicioIDResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO> ObtenerTipoServicioIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosTipoServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosTipoServicioResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO.ListaTipoServicios ObtenerTodosTipoServicio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosTipoServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosTipoServicioResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO.ListaTipoServicios> ObtenerTodosTipoServicioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrimerServicioChannel : Projecto_Final_PG4.Presentacion.SRComunicacionPersona.IPrimerServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimerServicioClient : System.ServiceModel.ClientBase<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.IPrimerServicio>, Projecto_Final_PG4.Presentacion.SRComunicacionPersona.IPrimerServicio {
        
        public PrimerServicioClient() {
        }
        
        public PrimerServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrimerServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimerServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimerServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertarPersona(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona) {
            base.Channel.InsertarPersona(persona);
        }
        
        public System.Threading.Tasks.Task InsertarPersonaAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona) {
            return base.Channel.InsertarPersonaAsync(persona);
        }
        
        public void ModificarPersona(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona) {
            base.Channel.ModificarPersona(persona);
        }
        
        public System.Threading.Tasks.Task ModificarPersonaAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona) {
            return base.Channel.ModificarPersonaAsync(persona);
        }
        
        public void EliminarPersona(string id) {
            base.Channel.EliminarPersona(id);
        }
        
        public System.Threading.Tasks.Task EliminarPersonaAsync(string id) {
            return base.Channel.EliminarPersonaAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO ObtenerPersonaID(string id) {
            return base.Channel.ObtenerPersonaID(id);
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO> ObtenerPersonaIDAsync(string id) {
            return base.Channel.ObtenerPersonaIDAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO.ListaPersonas ObtenerTodosPersona() {
            return base.Channel.ObtenerTodosPersona();
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO.ListaPersonas> ObtenerTodosPersonaAsync() {
            return base.Channel.ObtenerTodosPersonaAsync();
        }
        
        public void InsertarAutoCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cliente) {
            base.Channel.InsertarAutoCliente(cliente);
        }
        
        public System.Threading.Tasks.Task InsertarAutoClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cliente) {
            return base.Channel.InsertarAutoClienteAsync(cliente);
        }
        
        public void ModificarAutoCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cleinte) {
            base.Channel.ModificarAutoCliente(cleinte);
        }
        
        public System.Threading.Tasks.Task ModificarAutoClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cleinte) {
            return base.Channel.ModificarAutoClienteAsync(cleinte);
        }
        
        public void EliminarAutoCliente(int id) {
            base.Channel.EliminarAutoCliente(id);
        }
        
        public System.Threading.Tasks.Task EliminarAutoClienteAsync(int id) {
            return base.Channel.EliminarAutoClienteAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO ObtenerAutoClienteID(int id) {
            return base.Channel.ObtenerAutoClienteID(id);
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO> ObtenerAutoClienteIDAsync(int id) {
            return base.Channel.ObtenerAutoClienteIDAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO.ListaAutoCliente ObtenerTodosAutoClientes() {
            return base.Channel.ObtenerTodosAutoClientes();
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO.ListaAutoCliente> ObtenerTodosAutoClientesAsync() {
            return base.Channel.ObtenerTodosAutoClientesAsync();
        }
        
        public void InsertarServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio) {
            base.Channel.InsertarServicio(servicio);
        }
        
        public System.Threading.Tasks.Task InsertarServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio) {
            return base.Channel.InsertarServicioAsync(servicio);
        }
        
        public void ModificarServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio) {
            base.Channel.ModificarServicio(servicio);
        }
        
        public System.Threading.Tasks.Task ModificarServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio) {
            return base.Channel.ModificarServicioAsync(servicio);
        }
        
        public void EliminarServicio(int id) {
            base.Channel.EliminarServicio(id);
        }
        
        public System.Threading.Tasks.Task EliminarServicioAsync(int id) {
            return base.Channel.EliminarServicioAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO ObtenerServicioID(int id) {
            return base.Channel.ObtenerServicioID(id);
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO> ObtenerServicioIDAsync(int id) {
            return base.Channel.ObtenerServicioIDAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO.ListaServicios ObtenerTodosServicio() {
            return base.Channel.ObtenerTodosServicio();
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO.ListaServicios> ObtenerTodosServicioAsync() {
            return base.Channel.ObtenerTodosServicioAsync();
        }
        
        public void InsertarServicioCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO servicio) {
            base.Channel.InsertarServicioCliente(servicio);
        }
        
        public System.Threading.Tasks.Task InsertarServicioClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO servicio) {
            return base.Channel.InsertarServicioClienteAsync(servicio);
        }
        
        public void ModificarServicioCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO servicio) {
            base.Channel.ModificarServicioCliente(servicio);
        }
        
        public System.Threading.Tasks.Task ModificarServicioClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO servicio) {
            return base.Channel.ModificarServicioClienteAsync(servicio);
        }
        
        public void EliminarServicioCliente(int id) {
            base.Channel.EliminarServicioCliente(id);
        }
        
        public System.Threading.Tasks.Task EliminarServicioClienteAsync(int id) {
            return base.Channel.EliminarServicioClienteAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO ObtenerServicioClienteID(int id) {
            return base.Channel.ObtenerServicioClienteID(id);
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO> ObtenerServicioClienteIDAsync(int id) {
            return base.Channel.ObtenerServicioClienteIDAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO.ListaServiciosCliente ObtenerTodosServicioCliente() {
            return base.Channel.ObtenerTodosServicioCliente();
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosClienteDTO.ListaServiciosCliente> ObtenerTodosServicioClienteAsync() {
            return base.Channel.ObtenerTodosServicioClienteAsync();
        }
        
        public void InsertarAutomotor(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO automotor) {
            base.Channel.InsertarAutomotor(automotor);
        }
        
        public System.Threading.Tasks.Task InsertarAutomotorAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO automotor) {
            return base.Channel.InsertarAutomotorAsync(automotor);
        }
        
        public void ModificarAutomotor(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO automotor) {
            base.Channel.ModificarAutomotor(automotor);
        }
        
        public System.Threading.Tasks.Task ModificarAutomotorAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO automotor) {
            return base.Channel.ModificarAutomotorAsync(automotor);
        }
        
        public void EliminarAutomotor(int id) {
            base.Channel.EliminarAutomotor(id);
        }
        
        public System.Threading.Tasks.Task EliminarAutomotorAsync(int id) {
            return base.Channel.EliminarAutomotorAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO ObtenerAutomotorID(int id) {
            return base.Channel.ObtenerAutomotorID(id);
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO> ObtenerAutomotorIDAsync(int id) {
            return base.Channel.ObtenerAutomotorIDAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO.ListaAutomotores ObtenerTodosAutomotores() {
            return base.Channel.ObtenerTodosAutomotores();
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutomotoresDTO.ListaAutomotores> ObtenerTodosAutomotoresAsync() {
            return base.Channel.ObtenerTodosAutomotoresAsync();
        }
        
        public void InsertarTipoServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO tipoSrv) {
            base.Channel.InsertarTipoServicio(tipoSrv);
        }
        
        public System.Threading.Tasks.Task InsertarTipoServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO tipoSrv) {
            return base.Channel.InsertarTipoServicioAsync(tipoSrv);
        }
        
        public void ModificarTipoServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO tipoSrv) {
            base.Channel.ModificarTipoServicio(tipoSrv);
        }
        
        public System.Threading.Tasks.Task ModificarTipoServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO tipoSrv) {
            return base.Channel.ModificarTipoServicioAsync(tipoSrv);
        }
        
        public void EliminarTipoServicio(int id) {
            base.Channel.EliminarTipoServicio(id);
        }
        
        public System.Threading.Tasks.Task EliminarTipoServicioAsync(int id) {
            return base.Channel.EliminarTipoServicioAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO ObtenerTipoServicioID(int id) {
            return base.Channel.ObtenerTipoServicioID(id);
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO> ObtenerTipoServicioIDAsync(int id) {
            return base.Channel.ObtenerTipoServicioIDAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO.ListaTipoServicios ObtenerTodosTipoServicio() {
            return base.Channel.ObtenerTodosTipoServicio();
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.TipoServicioDTO.ListaTipoServicios> ObtenerTodosTipoServicioAsync() {
            return base.Channel.ObtenerTodosTipoServicioAsync();
        }
    }
}
