//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projecto_Final_PG4.Presentacion.SRComunicacionPersona {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaDTO", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
    [System.SerializableAttribute()]
    public partial class PersonaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_personaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_empleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((this.CelularField.Equals(value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsEmpleado {
            get {
                return this.EsEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EsEmpleadoField, value) != true)) {
                    this.EsEmpleadoField = value;
                    this.RaisePropertyChanged("EsEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_persona {
            get {
                return this.ID_personaField;
            }
            set {
                if ((this.ID_personaField.Equals(value) != true)) {
                    this.ID_personaField = value;
                    this.RaisePropertyChanged("ID_persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((this.TelefonoField.Equals(value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_empleado {
            get {
                return this.Tipo_empleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_empleadoField, value) != true)) {
                    this.Tipo_empleadoField = value;
                    this.RaisePropertyChanged("Tipo_empleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="PersonaDTO.ListaPersonas", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
        [System.SerializableAttribute()]
        public partial class ListaPersonas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO[] listaField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO[] lista {
                get {
                    return this.listaField;
                }
                set {
                    if ((object.ReferenceEquals(this.listaField, value) != true)) {
                        this.listaField = value;
                        this.RaisePropertyChanged("lista");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutoClienteDTO", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
    [System.SerializableAttribute()]
    public partial class AutoClienteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_Auto_Cliente1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Auto_Cliente1 {
            get {
                return this.ID_Auto_Cliente1Field;
            }
            set {
                if ((this.ID_Auto_Cliente1Field.Equals(value) != true)) {
                    this.ID_Auto_Cliente1Field = value;
                    this.RaisePropertyChanged("ID_Auto_Cliente1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AutoClienteDTO.ListaAutoCliente", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
        [System.SerializableAttribute()]
        public partial class ListaAutoCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO[] listaField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO[] lista {
                get {
                    return this.listaField;
                }
                set {
                    if ((object.ReferenceEquals(this.listaField, value) != true)) {
                        this.listaField = value;
                        this.RaisePropertyChanged("lista");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiciosDTO", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
    [System.SerializableAttribute()]
    public partial class ServiciosDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descripcion_servicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_servicio1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_tipo_servicio1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Servicio_seleccionadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion_servicio {
            get {
                return this.Descripcion_servicioField;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion_servicioField, value) != true)) {
                    this.Descripcion_servicioField = value;
                    this.RaisePropertyChanged("Descripcion_servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_servicio1 {
            get {
                return this.ID_servicio1Field;
            }
            set {
                if ((this.ID_servicio1Field.Equals(value) != true)) {
                    this.ID_servicio1Field = value;
                    this.RaisePropertyChanged("ID_servicio1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_tipo_servicio1 {
            get {
                return this.ID_tipo_servicio1Field;
            }
            set {
                if ((this.ID_tipo_servicio1Field.Equals(value) != true)) {
                    this.ID_tipo_servicio1Field = value;
                    this.RaisePropertyChanged("ID_tipo_servicio1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Servicio_seleccionado {
            get {
                return this.Servicio_seleccionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Servicio_seleccionadoField, value) != true)) {
                    this.Servicio_seleccionadoField = value;
                    this.RaisePropertyChanged("Servicio_seleccionado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ServiciosDTO.ListaServicios", Namespace="http://schemas.datacontract.org/2004/07/Projecto_Final_PG4.ComunicacionSApp")]
        [System.SerializableAttribute()]
        public partial class ListaServicios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO[] listaField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO[] lista {
                get {
                    return this.listaField;
                }
                set {
                    if ((object.ReferenceEquals(this.listaField, value) != true)) {
                        this.listaField = value;
                        this.RaisePropertyChanged("lista");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRComunicacionPersona.IPrimerServicio")]
    public interface IPrimerServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarPersonaResponse")]
        void InsertarPersona(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarPersonaResponse")]
        System.Threading.Tasks.Task InsertarPersonaAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarPersonaResponse")]
        void ModificarPersona(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarPersonaResponse")]
        System.Threading.Tasks.Task ModificarPersonaAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarPersonaResponse")]
        void EliminarPersona(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarPersona", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarPersonaResponse")]
        System.Threading.Tasks.Task EliminarPersonaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerPersonaID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerPersonaIDResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO ObtenerPersonaID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerPersonaID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerPersonaIDResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO> ObtenerPersonaIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodos", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO.ListaPersonas ObtenerTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodos", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO.ListaPersonas> ObtenerTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarAutoClienteResponse")]
        void InsertarAutoCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarAutoClienteResponse")]
        System.Threading.Tasks.Task InsertarAutoClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarAutoClienteResponse")]
        void ModificarAutoCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cleinte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarAutoClienteResponse")]
        System.Threading.Tasks.Task ModificarAutoClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cleinte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarAutoClienteResponse")]
        void EliminarAutoCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarAutoCliente", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarAutoClienteResponse")]
        System.Threading.Tasks.Task EliminarAutoClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerAutoClienteID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerAutoClienteIDResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO ObtenerAutoClienteID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerAutoClienteID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerAutoClienteIDResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO> ObtenerAutoClienteIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosClientes", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosClientesResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO.ListaAutoCliente ObtenerTodosClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosClientes", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosClientesResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO.ListaAutoCliente> ObtenerTodosClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarServicioResponse")]
        void InsertarServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/InsertarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/InsertarServicioResponse")]
        System.Threading.Tasks.Task InsertarServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarServicioResponse")]
        void ModificarServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ModificarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ModificarServicioResponse")]
        System.Threading.Tasks.Task ModificarServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarServicioResponse")]
        void EliminarServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/EliminarServicio", ReplyAction="http://tempuri.org/IPrimerServicio/EliminarServicioResponse")]
        System.Threading.Tasks.Task EliminarServicioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerServicioID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerServicioIDResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO ObtenerServicioID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerServicioID", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerServicioIDResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO> ObtenerServicioIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosServicioResponse")]
        Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO.ListaServicios ObtenerTodosServicio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimerServicio/ObtenerTodosServicio", ReplyAction="http://tempuri.org/IPrimerServicio/ObtenerTodosServicioResponse")]
        System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO.ListaServicios> ObtenerTodosServicioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrimerServicioChannel : Projecto_Final_PG4.Presentacion.SRComunicacionPersona.IPrimerServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimerServicioClient : System.ServiceModel.ClientBase<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.IPrimerServicio>, Projecto_Final_PG4.Presentacion.SRComunicacionPersona.IPrimerServicio {
        
        public PrimerServicioClient() {
        }
        
        public PrimerServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrimerServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimerServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimerServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertarPersona(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona) {
            base.Channel.InsertarPersona(persona);
        }
        
        public System.Threading.Tasks.Task InsertarPersonaAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona) {
            return base.Channel.InsertarPersonaAsync(persona);
        }
        
        public void ModificarPersona(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona) {
            base.Channel.ModificarPersona(persona);
        }
        
        public System.Threading.Tasks.Task ModificarPersonaAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO persona) {
            return base.Channel.ModificarPersonaAsync(persona);
        }
        
        public void EliminarPersona(int id) {
            base.Channel.EliminarPersona(id);
        }
        
        public System.Threading.Tasks.Task EliminarPersonaAsync(int id) {
            return base.Channel.EliminarPersonaAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO ObtenerPersonaID(int id) {
            return base.Channel.ObtenerPersonaID(id);
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO> ObtenerPersonaIDAsync(int id) {
            return base.Channel.ObtenerPersonaIDAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO.ListaPersonas ObtenerTodos() {
            return base.Channel.ObtenerTodos();
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.PersonaDTO.ListaPersonas> ObtenerTodosAsync() {
            return base.Channel.ObtenerTodosAsync();
        }
        
        public void InsertarAutoCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cliente) {
            base.Channel.InsertarAutoCliente(cliente);
        }
        
        public System.Threading.Tasks.Task InsertarAutoClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cliente) {
            return base.Channel.InsertarAutoClienteAsync(cliente);
        }
        
        public void ModificarAutoCliente(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cleinte) {
            base.Channel.ModificarAutoCliente(cleinte);
        }
        
        public System.Threading.Tasks.Task ModificarAutoClienteAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO cleinte) {
            return base.Channel.ModificarAutoClienteAsync(cleinte);
        }
        
        public void EliminarAutoCliente(int id) {
            base.Channel.EliminarAutoCliente(id);
        }
        
        public System.Threading.Tasks.Task EliminarAutoClienteAsync(int id) {
            return base.Channel.EliminarAutoClienteAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO ObtenerAutoClienteID(int id) {
            return base.Channel.ObtenerAutoClienteID(id);
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO> ObtenerAutoClienteIDAsync(int id) {
            return base.Channel.ObtenerAutoClienteIDAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO.ListaAutoCliente ObtenerTodosClientes() {
            return base.Channel.ObtenerTodosClientes();
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.AutoClienteDTO.ListaAutoCliente> ObtenerTodosClientesAsync() {
            return base.Channel.ObtenerTodosClientesAsync();
        }
        
        public void InsertarServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio) {
            base.Channel.InsertarServicio(servicio);
        }
        
        public System.Threading.Tasks.Task InsertarServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio) {
            return base.Channel.InsertarServicioAsync(servicio);
        }
        
        public void ModificarServicio(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio) {
            base.Channel.ModificarServicio(servicio);
        }
        
        public System.Threading.Tasks.Task ModificarServicioAsync(Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO servicio) {
            return base.Channel.ModificarServicioAsync(servicio);
        }
        
        public void EliminarServicio(int id) {
            base.Channel.EliminarServicio(id);
        }
        
        public System.Threading.Tasks.Task EliminarServicioAsync(int id) {
            return base.Channel.EliminarServicioAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO ObtenerServicioID(int id) {
            return base.Channel.ObtenerServicioID(id);
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO> ObtenerServicioIDAsync(int id) {
            return base.Channel.ObtenerServicioIDAsync(id);
        }
        
        public Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO.ListaServicios ObtenerTodosServicio() {
            return base.Channel.ObtenerTodosServicio();
        }
        
        public System.Threading.Tasks.Task<Projecto_Final_PG4.Presentacion.SRComunicacionPersona.ServiciosDTO.ListaServicios> ObtenerTodosServicioAsync() {
            return base.Channel.ObtenerTodosServicioAsync();
        }
    }
}
