// <auto-generated />
namespace Projecto_Final_PG4.AccesoDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class PrimerMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrimerMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202104062128139_PrimerMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
